# ░██╗░░░░░░░██╗░█████╗░████████╗███████╗██████╗░██████╗░██╗███╗░░██╗░██████╗░
# ░██║░░██╗░░██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██║████╗░██║██╔════╝░
# ░╚██╗████╗██╔╝███████║░░░██║░░░█████╗░░██████╔╝██████╔╝██║██╔██╗██║██║░░██╗░
# ░░████╔═████║░██╔══██║░░░██║░░░██╔══╝░░██╔══██╗██╔═══╝░██║██║╚████║██║░░╚██╗
# ░░╚██╔╝░╚██╔╝░██║░░██║░░░██║░░░███████╗██║░░██║██║░░░░░██║██║░╚███║╚██████╔╝
# ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚══╝░╚═════╝░

#WaterPing - BungeeCord Ping System
#Support - https://github.com/RDProjectOfficial

#Settings
Prefix: "§8• §bWaterPing §8× "
NoPermission: "§bYou do not have permission!"

#Message
ping-message: "§7Your ping is §b%ping% §7ms!"
ping-other-message: "§7The ping of §b%target% §7is §b%ping% §7ms!"
player-not-found: "§bThis player is not online!"